### ISSUE TITLE
launch file

### ISSUE THREAD

**Issue by fgonzalezr1998** [Eruvae/yolact_ros#1]
I think, system would improve adding a launch file. In this way, camera topic could be defined when launch file is launched and user do not have to change this topic in the source code. This is one thing I did when I used yolact_ros.

**Comment by Mojojojooo** [comment]
Hey seems like you were successful in using the package. Can you help me set it up?

**Comment by fgonzalezr1998** [comment]
@Mojojojooo Of course!

**Comment by fgonzalezr1998** [comment]
What is your problem? @Mojojojooo

**Comment by Mojojojooo** [comment]
I am also facing an error while using your Launch file.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/22592311/86580698-b0309a00-bf9c-11ea-847f-8f4841050081.png)

**Comment by fgonzalezr1998** [comment]
Write an Issue in my repository to speak about that, please @Mojojojooo

**Comment by Mojojojooo** [comment]
@fgonzalezr1998 How do I do that there is no issue option in your repo ?

**Comment by fgonzalezr1998** [comment]
I am going to enumerate the steps to be able to have yolact_ros running with my version (with launcher).

* Clone my repo (branch *launch_file*) and compile it with options specified in the README because it uses Python3.

* Run camera driver

* Change in the launcher file, it is necessary, the topic name where RGB image is published

* Run ``roslaunch yolact_ros yolact_ros.launch``

Ii should work but, if it doesn't, tell me in which step it fails and provide me as information as possible. @Mojojojooo

**Comment by fgonzalezr1998** [comment]
@Mojojojooo There was an error in the launcher file, I have just corrected it. Now, it works properly
