### ISSUE TITLE
Please add support for yolact-edge and its tensorrt support

### ISSUE THREAD

**Issue by FPSychotic** [Eruvae/yolact_ros#16]
the above would be great if it is enough easy or you are interested.
i have a Jetson NX running it already if you need help to test let me know,I dont know coding or AI but I can test or give you online access to you can try whatever you want.
thanks!!

**Comment by Eruvae** [comment]
I added a new file "yolact_edge_ros" that loads yolact_edge from the new submodule (a forked version of the original repository with some fixes to the load_weight function). You can start it with "rosrun yolact_ros yolact_edge_ros". Feel free to test it and let me know if it works.

**Comment by FPSychotic** [comment]
Wow, thanks. Im going to test it and  give you all the info I can of how it runs. 
In stardar resolution 512x512, TRT converted it runs at 10fps in the Xavier NX, I looking to low the resolution as it is not needed , I'm investigating all this as I have no idea LoL.
I will test your other  software as semantic mapping and hypermaps , they sound fantastic!
Thanks for share!

**Comment by FPSychotic** [comment]
starting the tests, I installed your fork, at the moment the frame speed is the same, and it works, but  received this messages . the gsstreamer and timer running before they wasn't I think. 
i have more frames in the buffer, previously 1 or 2 , now 4-6 , I dont know if it is good or bad. it cold be because now s dark and the camera performs worse.

the messages
```
[ WARN:0] global /tmp/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Initializing model... Done.
Number of threads: 4

Processing FPS: 7.60 | Video Playback FPS: 8.65 | Frames in Buffer: 3    Warning: timer stopped with no timer running!
Processing FPS: 9.76 | Video Playback FPS: 9.27 | Frames in Buffer: 5

```
Next the ros wrapper but is a little complicated to install for me XD
