### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Yolact:

### ISSUE THREAD

**Issue by PSQzzzxk** [Eruvae/yolact_ros#19]
Hi,Eruvae,I encountered such a problem with the .pth file I trained. This weight can be used in  yolact/dbolya  package, but it cannot be used in the yolact_ros package. Do you have any solutions?

Here is my command：
rosrun yolact_ros yolact_ros _model_path:="$(rospack find yolact_ros)/scripts/yolact/weights/yolact_base_1764_30000.pth" _image_topic:="/node_a"

And this is my feedback:
Traceback (most recent call last):
  File "/home/fido/yolros_ws/src/yolact_ros/scripts/yolact_ros", line 434, in <module>
    main(sys.argv)
  File "/home/fido/yolros_ws/src/yolact_ros/scripts/yolact_ros", line 419, in main
    net.load_weights(model_path_str)
  File "/home/fido/yolros_ws/src/yolact_ros/scripts/yolact/yolact.py", line 491, in load_weights
    self.load_state_dict(state_dict)
  File "/home/fido/anaconda3/envs/yolact/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolact:
	size mismatch for prediction_layers.0.conf_layer.weight: copying a param with shape torch.Size([6, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([243, 256, 3, 3]).
	size mismatch for prediction_layers.0.conf_layer.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([243]).
	size mismatch for semantic_seg_conv.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for semantic_seg_conv.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).

**Comment by Eruvae** [comment]
There seems to be a size mismatch in your model configuration. Did you train with custom classes? The configuration expects 80 classes as input (the 80 coco classes for the default yolact_base configuration), your model seems to have only one class.
If you have customized yolact, e.g. with your own config, make sure that this custom version is also the one in the scripts folder (if you only modified the configuration, it might be enough to copy your version of config.py to the yolact data folder).

**Comment by PSQzzzxk** [comment]
My problem is solved, thanks a lot!
