### ISSUE TITLE
Type in yoloact_ros script - net:Yoloact

### ISSUE THREAD

**Issue by mfinean** [Eruvae/yolact_ros#21]
https://github.com/Eruvae/yolact_ros/blob/9ad3baf718b354ff2085dd1087f56c7ed9fab997/scripts/yolact_ros#L76

replace 
`net:Yoloact` 
with 
`net`

**Comment by Eruvae** [comment]
Type specifications like this are supported in Python 3. If this was the only change that would make this node compatible with Python 2, I'd consider changing it, but I'm pretty sure Yolact doesn't support Python 2.

**Comment by mfinean** [comment]
Ah yes, agreed. Multiple changes are needed.
