### ISSUE TITLE
how to build pytorch for ros

### ISSUE THREAD

**Issue by akshayacharya97** [Eruvae/yolact_ros#23]
The repo needs pytorch for running. How do i install pytorch on python2 for ros?

**Comment by Eruvae** [comment]
Pytorch dropped Python 2 support a while ago. While it should be possible to install an old version, Yolact also requires Python 3, so you still couldn't run this. You either have to use ROS noetic, which uses Python 3 by default (recommended if possible), or compile this package in a separate Python 3 workspace (see instructions in the readme). The latter can be a bit tricky, so if your other packages support ROS noetic, it would be easier to switch.
