### ISSUE TITLE
ROS2 Integration

### ISSUE THREAD

**Issue by fgonzalezr1998** [Eruvae/yolact_ros#4]
Hello, I think that *yolact_ros* could be integrated with ROS2. I'd like to work on that. If you think this is a good idea, you could create a new branch for ROS2

**Comment by Eruvae** [comment]
You can work on ROS2 integration if you want. I haven't used ROS2 yet, so I have no experience with it. I can add you as collaborator to this repository and the message repository, and then you can work on ROS2 branches.

**Comment by fgonzalezr1998** [comment]
Thanks! I've seen the ROS2 branch in *yolact_ros_msgs* repository. I am going to start working on that

**Comment by fgonzalezr1998** [comment]
I am already working successfully on ROS2 migration
